// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} now
 * @param {string} to
 * @returns {$CancellablePromise<[($models.CommitItem | null)[], ($models.CommitItemFile | null)[]]>}
 */
export function AutoGetCommitsList(now, to) {
    return $Call.ByID(1657066054, now, to).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType2($result[0]);
        $result[1] = $$createType5($result[1]);
        return $result;
    }));
}

/**
 * @param {string} sha
 * @returns {$CancellablePromise<$models.CommitItem | null>}
 */
export function GetCommit(sha) {
    return $Call.ByID(1122172792, sha).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} page
 * @param {number} perPage
 * @returns {$CancellablePromise<($models.CommitItem | null)[]>}
 */
export function GetCommits(page, perPage) {
    return $Call.ByID(1448574545, page, perPage).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} page
 * @param {number} perPage
 * @param {string} state
 * @returns {$CancellablePromise<($models.IsuessItem | null)[]>}
 */
export function GetIssues(page, perPage, state) {
    return $Call.ByID(4248570885, page, perPage, state).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<($models.Label | null)[]>}
 */
export function GetLabels() {
    return $Call.ByID(248134366).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.User | null>}
 */
export function GetMe() {
    return $Call.ByID(1814506019).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RepoItem | null>}
 */
export function GetRepo() {
    return $Call.ByID(4019833401).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} username
 * @returns {$CancellablePromise<$models.User | null>}
 */
export function GetUser(username) {
    return $Call.ByID(913854558, username).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenOauthWindow() {
    return $Call.ByID(1101953366);
}

/**
 * @param {string} CLIENT_ID
 * @returns {$CancellablePromise<void>}
 */
export function StartOAuth(CLIENT_ID) {
    return $Call.ByID(3229709228, CLIENT_ID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopOAuth() {
    return $Call.ByID(2788071774);
}

// Private type creation functions
const $$createType0 = $models.CommitItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.CommitItemFile.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.IsuessItem.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.Label.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.User.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.RepoItem.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
