// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ColorARGB {
    /**
     * Creates a new ColorARGB instance.
     * @param {Partial<ColorARGB>} [$$source = {}] - The source object to create the ColorARGB.
     */
    constructor($$source = {}) {
        if (!("A" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["A"] = 0;
        }
        if (!("R" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["R"] = 0;
        }
        if (!("G" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["G"] = 0;
        }
        if (!("B" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["B"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorARGB instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColorARGB}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColorARGB(/** @type {Partial<ColorARGB>} */($$parsedSource));
    }
}
