// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} key
 * @param {any} value
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function ChangeConfig(key, value) {
    return $Call.ByID(620895718, key, value).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} key
 * @param {any} value
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function ChangeConfigAndSave(key, value) {
    return $Call.ByID(1866601402, key, value).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetConfig() {
    return $Call.ByID(1130451578).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<any>}
 */
export function GetConfigValue(key) {
    return $Call.ByID(2546488867, key);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLogin() {
    return $Call.ByID(2273979125);
}

/**
 * 退出登录
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(1011445894);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig() {
    return $Call.ByID(258543615);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UserData() {
    return $Call.ByID(1454511483);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
